package ar.com.logistics.shipment.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Maps to {@code public.shipments} (V15). The central aggregate root
 * of the logistics domain. RLS-scoped via V16.
 *
 * <p>{@code trackingId} is the public-facing LGST-XXXXXXXX code
 * generated by {@code LgstGeneratorService}; it carries a UNIQUE
 * constraint across the whole platform (not per tenant) so any two
 * tenants can never collide. The {@code shipments_status} CHECK
 * accepts {@code PRE_ALTA}, {@code EN_PREPARACION}, etc. — the full
 * enum is bounded by the {@link PackageFsm} + status calculator
 * introduced in PR-2.
 *
 * <p>FK associations ({@code senderId}, {@code receiverId},
 * {@code deliveryAddressId}, branches, service level) are kept as
 * primitive UUID refs — JPA associations land in PR-3a when the
 * shipment-creation service is built.
 */
@Entity
@Table(name = "shipments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Shipment {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "tenant_id", nullable = false, updatable = false)
    private UUID tenantId;

    @Column(name = "tracking_id", length = 13, nullable = false, unique = true)
    private String trackingId;

    @Column(name = "code", length = 20)
    private String code;

    @Column(name = "shipment_type", length = 20, nullable = false)
    private String shipmentType;

    @Column(name = "parent_shipment_id")
    private UUID parentShipmentId;

    @Column(name = "sender_id", nullable = false)
    private UUID senderId;

    @Column(name = "receiver_id", nullable = false)
    private UUID receiverId;

    @Column(name = "delivery_address_id", nullable = false)
    private UUID deliveryAddressId;

    @Column(name = "origin_branch_id", nullable = false)
    private UUID originBranchId;

    @Column(name = "destination_branch_id", nullable = false)
    private UUID destinationBranchId;

    @Column(name = "service_level_id", nullable = false)
    private UUID serviceLevelId;

    @Column(name = "payment_type", length = 30, nullable = false)
    private String paymentType;

    @Column(name = "delivery_mode", length = 30, nullable = false)
    private String deliveryMode;

    @Column(name = "delivery_instructions", columnDefinition = "TEXT")
    private String deliveryInstructions;

    @Column(name = "status", length = 50, nullable = false)
    private String status;

    @Column(name = "promised_delivery_date")
    private LocalDate promisedDeliveryDate;

    @Column(name = "sla_status", length = 20, nullable = false)
    private String slaStatus;

    @Column(name = "total_weight_kg", precision = 8, scale = 2)
    private BigDecimal totalWeightKg;

    @Column(name = "total_cost", precision = 12, scale = 2)
    private BigDecimal totalCost;

    @Column(name = "created_by", nullable = false)
    private UUID createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Column(name = "deleted_at")
    private Instant deletedAt;

    @jakarta.persistence.PrePersist
    void onCreate() {
        Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        this.updatedAt = now;
    }

    @jakarta.persistence.PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now();
    }
}
